name: Update Info to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "public/info.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-if-info-changed-only:
    runs-on: ubuntu-latest
    outputs:
      info_changed: ${{ steps.check.outputs.info_changed }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Check if only info.json changed
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "✅ 手动触发，跳过文件检查，直接执行后续步骤"
            echo "info_changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          ONLY_INFO_JSON=true
          for f in $CHANGED_FILES; do
            if [ "$f" != "public/info.json" ]; then
              ONLY_INFO_JSON=false
            fi
          done

          echo "only_info_json=$ONLY_INFO_JSON"
          echo "info_changed=$ONLY_INFO_JSON" >> $GITHUB_OUTPUT


  build:
    needs: check-if-info-changed-only
    if: needs.check-if-info-changed-only.outputs.info_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Download dist artifact
        uses: dawidd6/action-download-artifact@v14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: nuxtjs.yml
          name: github-pages
          path: ./dist
      
      - name: untar dist artifact
        run: |
          echo "Files in dist directory before untar:"
          ls -la ./dist
          tar -xzf ./dist/dist.zip -C ./dist
          echo "Files in dist directory after untar:"
          ls -la ./dist

      - name: Copy info.json to dist
        run: cp public/info.json ./dist/info.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: [build, check-if-info-changed-only]
    if: needs.check-if-info-changed-only.outputs.info_changed == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
